# coding: utf-8

"""
    Fleet v2 HTTP API

    Development version of a the API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from http_api_client.models.connect_to_database_request import ConnectToDatabaseRequest  # noqa: E501

class TestConnectToDatabaseRequest(unittest.TestCase):
    """ConnectToDatabaseRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConnectToDatabaseRequest:
        """Test ConnectToDatabaseRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConnectToDatabaseRequest`
        """
        model = ConnectToDatabaseRequest()  # noqa: E501
        if include_optional:
            return ConnectToDatabaseRequest(
                dialect = 'postgresql',
                engine = 'psycopg',
                location = 'localhost:8080',
                username = 'username',
                password = '1234'
            )
        else:
            return ConnectToDatabaseRequest(
        )
        """

    def testConnectToDatabaseRequest(self):
        """Test ConnectToDatabaseRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
