# coding: utf-8

"""
    Fleet v2 HTTP API

    Development version of a the API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from http_api_client.api.database_api import DatabaseApi  # noqa: E501


class TestDatabaseApi(unittest.TestCase):
    """DatabaseApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DatabaseApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_connect_to_database(self) -> None:
        """Test case for connect_to_database

        """
        pass


if __name__ == '__main__':
    unittest.main()
