# coding: utf-8

"""
    Fleet v2 HTTP API

    Development version of a the API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from http_api_client.models.message import Message  # noqa: E501

class TestMessage(unittest.TestCase):
    """Message unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Message:
        """Test Message
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Message`
        """
        model = Message()  # noqa: E501
        if include_optional:
            return Message(
                timestamp = 1699262836,
                id = {"moduleid":47,"type":2,"role":"test_device","name":"Test Device"},
                payload = {"type":0,"encoding":1,"data":"QnJpbmdBdXRv"}
            )
        else:
            return Message(
        )
        """

    def testMessage(self):
        """Test Message"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
