# coding: utf-8

"""
    Fleet v2 HTTP API

    Development version of a the API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from http_api_client.api.device_api import DeviceApi  # noqa: E501


class TestDeviceApi(unittest.TestCase):
    """DeviceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeviceApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_available_devices(self) -> None:
        """Test case for available_devices

        """
        pass

    def test_list_commands(self) -> None:
        """Test case for list_commands

        """
        pass

    def test_list_statuses(self) -> None:
        """Test case for list_statuses

        """
        pass

    def test_send_commands(self) -> None:
        """Test case for send_commands

        """
        pass

    def test_send_statuses(self) -> None:
        """Test case for send_statuses

        """
        pass


if __name__ == '__main__':
    unittest.main()
