# coding: utf-8

"""
    Fleet v2 HTTP API

    Development version of a the API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from http_api_client.models.car import Car  # noqa: E501

class TestCar(unittest.TestCase):
    """Car unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Car:
        """Test Car
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Car`
        """
        model = Car()  # noqa: E501
        if include_optional:
            return Car(
                company_name = 'bringauto',
                car_name = 'piba09223'
            )
        else:
            return Car(
                company_name = 'bringauto',
                car_name = 'piba09223',
        )
        """

    def testCar(self):
        """Test Car"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
