version: '3.0'

services:

  server:
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresql-database
    ports:
      - 8080:8080
    networks:
      - api-network
    entrypoint:
      ["python3", "-m", "server", "config.json", "--location", "postgresql-database"]

  postgresql-database:
    image: postgres:16
    restart: "no"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    networks:
      - api-network
    ports:
      - 5432:5432

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.3
    restart: "no"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8081:8080
    networks:
      - api-network
    command: "start-dev"

networks:
  api-network:
