openapi: 3.0.2


info:
  title: Fleet v2 HTTP API
  version: 0.1.0
  description: Development version of a the API


servers:
  - url: http://localhost:8080
  - url: http://localhost:8080/{company-name}/{car-name}
    variables:
      company-name: 
        default: bringauto
        description: Name of the company
      car-name:
        default: carname 
        description: Name of the car


tags: 
- name: car
- name: device


paths:
  /cars:
    servers:
      - url: http://localhost:8080
    get:
      x-openapi-router-controller: fleetv2_http_api.impl.car_controller
      operationId: cars_available
      description: It returns the list of available Cars.
      tags: 
        - car
      responses:
        '200':
          description: A list of available cars. 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Car'
              example:
                [{company-name: 'bringauto', car-name: 'piba0258'}]
        '500':
          description: Cannot display avaialble cars due to internal server error.


  /available-devices:
    servers:
    - url: http://localhost:8080/{company-name}/{car-name}
    get:
      x-openapi-router-controller: fleetv2_http_api.impl.device_controller
      operationId: devices_available
      description: Returns list of available devices for the whole car or a single module.
      tags: 
        - device
      responses:
        '200':
          description: A list of available devices. 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DeviceId'

        
        '500':
          description: Cannot display available devices due to internal server error.

    parameters:
      - $ref: "#/components/parameters/ModuleId"
      

  /status/{device-id}:
    servers:
    - url: http://localhost:8080/{company-name}/{car-name}
    get:
      x-openapi-router-controller: fleetv2_http_api.impl.device_controller
      operationId: list_statuses
      description: It returns list of the Device Statuses.
      tags: 
      - device
      responses:
        '200':
          description: A list of device statuses.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Payload'
        '500':
          description: The statuses cannot be displayed due to internal server error.
    post:
      x-openapi-router-controller: fleetv2_http_api.impl.device_controller
      operationId: send_statuses
      description: Add statuses received from the Device.
      tags: 
      - device
      responses:
        '200':
          description: The statuses have been sent.
        '500':
          description: The statuses could not been sent due to internal server error.
      requestBody:
        description: Commands to be executed by the device.
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Payload'

    parameters:
      - $ref: '#/components/parameters/All'
      - $ref: '#/components/parameters/Since'
      - $ref: '#/components/parameters/DeviceId'


  /command/{device-id}:
    servers:
    - url: http://localhost:8080/{company-name}/{car-name}
    get:
      x-openapi-router-controller: fleetv2_http_api.impl.device_controller
      operationId: list_commands
      description: Returns list of the Device Commands.
      tags: 
      - device
      responses:
        '200':
          description: A list of commands.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Payload'
      
        '500':
          description: The commands cannot be displayed due to internal server error.
          
    post:
      x-openapi-router-controller: fleetv2_http_api.impl.device_controller
      operationId: send_commands
      description: It adds new device Commands.
      tags: 
      - device
      requestBody:
        description: Commands to be executed by the device.
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Payload'
      responses:
        '200':
          description: The commands have been sent.
        '500':
          description: The commands have not been sent due to internal server error.

    parameters:
      - $ref: '#/components/parameters/All'
      - $ref: '#/components/parameters/Since'
      - $ref: '#/components/parameters/DeviceId'

components:
  parameters:
    All: 
      name: all 
      description: If set, the method returns a complete history of statuses/commands.
      in: query
      allowEmptyValue: true
      schema: 
        type: boolean
      example: false

    Since:
      name: since
      description: A Unix timestamp; if specified, the method returns all device statuses/commands inclusivelly older than value of specified timestamp.
      in: query
      allowEmptyValue: false 
      schema: 
        type: integer
      example: 1699262836

    ModuleId:
      name: module-id
      description: An Id of module.
      in: query
      allowEmptyValue: true
      schema: 
        minimum: 0
      example: 785

    DeviceId:
      name: device-id
      description: The Id of the Device. 
      in: path
      required: true
      schema:
        type: integer
        minimum: 0
      example: 45


  schemas:
    Car:
      description: The subject of control.
      type: object
      required:
        - company-name
        - car-name
      properties:
        company-name:
          type: string
          minLength: 1
          example: "bringauto"        
        car-name:
          type: string
          minLength: 1
          example: piba09223
    
    Message: 
      description: Physical device or program located on the car.
      type: object 
      properties: 
        timestamp: 
          type: integer 
          minimum: 0 
          example: 1699262836
        id: 
          $ref: '#/components/schemas/DeviceId'
        payload:
          $ref: '#/components/schemas/Payload'

    DeviceId: 
      description: The Id of a device. 
      type: object
      properties:
        module_id: 
          $ref: '#/components/schemas/Id'
        type:
          type: integer
          minimum: 0
          example: 1
        role:
          type: string
          example: "Warning LED"
        name: 
          type: string
          example: "Left red LED"

    Payload: 
      description: A message passed to device (command) or by device (status).
      type: object
      properties:
        type: 
          type: integer 
          minimum: 0
          example: 4
        encoding:
          type: string
          example: BASE64
        data:
          type: object
          example: 
            main_text: The device is running.
        
                

    Id: 
      description: A general integer Id
      type: integer 
      minimum: 0 
      example: 42
