# coding: utf-8

# flake8: noqa
"""
    Fleet v2 HTTP API

    Development version of a the API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from http_api_client.models.car import Car
from http_api_client.models.device_id import DeviceId
from http_api_client.models.message import Message
from http_api_client.models.module import Module
from http_api_client.models.payload import Payload
