# coding: utf-8

"""
    Fleet v2 HTTP API

    Development version of a the API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, conint, conlist
from http_api_client.models.device_id import DeviceId

class Module(BaseModel):
    """
    Car module, representing set of Device  # noqa: E501
    """
    id: conint(strict=True, ge=0) = Field(..., description="A general integer Id")
    device_list: conlist(DeviceId) = Field(..., alias="device-list")
    __properties = ["id", "device-list"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Module:
        """Create an instance of Module from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in device_list (list)
        _items = []
        if self.device_list:
            for _item in self.device_list:
                if _item:
                    _items.append(_item.to_dict())
            _dict['device-list'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Module:
        """Create an instance of Module from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Module.parse_obj(obj)

        _obj = Module.parse_obj({
            "id": obj.get("id"),
            "device_list": [DeviceId.from_dict(_item) for _item in obj.get("device-list")] if obj.get("device-list") is not None else None
        })
        return _obj


