from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fleetv2_http_api.models.base_model import Model
from fleetv2_http_api import util


class Payload(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, encoding=None, data=None):  # noqa: E501
        """Payload - a model defined in OpenAPI

        :param type: The type of this Payload.  # noqa: E501
        :type type: int
        :param encoding: The encoding of this Payload.  # noqa: E501
        :type encoding: str
        :param data: The data of this Payload.  # noqa: E501
        :type data: object
        """
        self.openapi_types = {
            'type': int,
            'encoding': str,
            'data': object
        }

        self.attribute_map = {
            'type': 'type',
            'encoding': 'encoding',
            'data': 'data'
        }

        self._type = type
        self._encoding = encoding
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'Payload':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Payload of this Payload.  # noqa: E501
        :rtype: Payload
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> int:
        """Gets the type of this Payload.


        :return: The type of this Payload.
        :rtype: int
        """
        return self._type

    @type.setter
    def type(self, type: int):
        """Sets the type of this Payload.


        :param type: The type of this Payload.
        :type type: int
        """
        if type is not None and type < 0:  # noqa: E501
            raise ValueError("Invalid value for `type`, must be a value greater than or equal to `0`")  # noqa: E501

        self._type = type

    @property
    def encoding(self) -> str:
        """Gets the encoding of this Payload.


        :return: The encoding of this Payload.
        :rtype: str
        """
        return self._encoding

    @encoding.setter
    def encoding(self, encoding: str):
        """Sets the encoding of this Payload.


        :param encoding: The encoding of this Payload.
        :type encoding: str
        """

        self._encoding = encoding

    @property
    def data(self) -> object:
        """Gets the data of this Payload.


        :return: The data of this Payload.
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data: object):
        """Sets the data of this Payload.


        :param data: The data of this Payload.
        :type data: object
        """

        self._data = data
