from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fleetv2_http_api.models.base_model import Model
from fleetv2_http_api.models.payload_data import PayloadData
from fleetv2_http_api import util

from fleetv2_http_api.models.payload_data import PayloadData  # noqa: E501

class Payload(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, encoding=None, data=None):  # noqa: E501
        """Payload - a model defined in OpenAPI

        :param type: The type of this Payload.  # noqa: E501
        :type type: int
        :param encoding: The encoding of this Payload.  # noqa: E501
        :type encoding: int
        :param data: The data of this Payload.  # noqa: E501
        :type data: PayloadData
        """
        self.openapi_types = {
            'type': int,
            'encoding': int,
            'data': PayloadData
        }

        self.attribute_map = {
            'type': 'type',
            'encoding': 'encoding',
            'data': 'data'
        }

        self._type = type
        self._encoding = encoding
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'Payload':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Payload of this Payload.  # noqa: E501
        :rtype: Payload
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> int:
        """Gets the type of this Payload.

        Type of the payload, enumerated as follows: <br> 0 - STATUS <br> 1 - COMMAND  # noqa: E501

        :return: The type of this Payload.
        :rtype: int
        """
        return self._type

    @type.setter
    def type(self, type: int):
        """Sets the type of this Payload.

        Type of the payload, enumerated as follows: <br> 0 - STATUS <br> 1 - COMMAND  # noqa: E501

        :param type: The type of this Payload.
        :type type: int
        """

        self._type = type

    @property
    def encoding(self) -> int:
        """Gets the encoding of this Payload.

        Encoding of the payload, enumerated as follows: <br> 0 - JSON <br> 1 - BASE64  # noqa: E501

        :return: The encoding of this Payload.
        :rtype: int
        """
        return self._encoding

    @encoding.setter
    def encoding(self, encoding: int):
        """Sets the encoding of this Payload.

        Encoding of the payload, enumerated as follows: <br> 0 - JSON <br> 1 - BASE64  # noqa: E501

        :param encoding: The encoding of this Payload.
        :type encoding: int
        """

        self._encoding = encoding

    @property
    def data(self) -> PayloadData:
        """Gets the data of this Payload.


        :return: The data of this Payload.
        :rtype: PayloadData
        """
        return self._data

    @data.setter
    def data(self, data: PayloadData):
        """Sets the data of this Payload.


        :param data: The data of this Payload.
        :type data: PayloadData
        """

        self._data = data
