from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server.fleetv2_http_api.models.base_model import Model
from server.fleetv2_http_api import util


class PayloadData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """PayloadData - a model defined in OpenAPI"""
        self.openapi_types = {}

        self.attribute_map = {}

    @classmethod
    def from_dict(cls, dikt) -> "PayloadData":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Payload_data of this PayloadData.  # noqa: E501
        :rtype: PayloadData
        """
        return util.deserialize_model(dikt, cls)
